'use strict';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={catalog:null,example:null,result:null,selected:0,dirty:false,busy:false,ready:false,ruleCategory:'全部',testResults:[],testFilter:'all',testReport:null};
const labels={correct:'已验证正确',wrong:'已确认错误',unknown:'暂无法判断',incomplete:'缺少收敛域',error:'输入错误'};
let worker,sequence=0;const pending=new Map();
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function math(tex,fallback){if(tex&&window.katex){try{return katex.renderToString(tex,{throwOnError:false,strict:false,trust:false});}catch(e){}}return esc(fallback);}
function switchView(view){if(!['verify','rules','tests','guide'].includes(view))view='verify';$$('.view').forEach(e=>e.classList.toggle('active',e.id===view+'-view'));$$('.nav').forEach(e=>e.classList.toggle('active',e.dataset.view===view));$('#page-crumb').textContent={verify:'推导验证',rules:'规则图谱',tests:'验收测试',guide:'使用与约定'}[view];if(location.hash!=='#'+view)history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'smooth'});}
$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));window.addEventListener('hashchange',()=>switchView(location.hash.slice(1)));
function setBusy(v){state.busy=v;$('#verify-btn').disabled=v||!state.ready;$('#run-tests').disabled=v||!state.ready;$('#verify-btn').classList.toggle('busy',v);$('#verify-btn').innerHTML=v?'正在符号验证…':'<span>▶</span> 验证推导';$$('.repair-button').forEach(x=>x.disabled=v);}
function request(payload,progress){return new Promise((resolve,reject)=>{if(!state.ready)return reject(Error('数学引擎尚未就绪，请稍候。'));const id=++sequence;const timeout=setTimeout(()=>{pending.delete(id);worker.terminate();state.ready=false;$('#engine-state').className='engine-pill error';$('#engine-state span').textContent='计算超时 · 点击重启';setBusy(false);reject(Error('计算超出时间上限。请拆分步骤，并点击右上角重启引擎。'));},payload.action==='tests'?300000:35000);pending.set(id,{resolve,reject,timeout,progress});worker.postMessage({id,request:payload});});}
function startWorker(){
 if(worker)worker.terminate();state.ready=false;$('#engine-state').className='engine-pill';$('#engine-state span').textContent='正在载入数学引擎';worker=new Worker('worker.js');
 worker.onmessage=({data})=>{
  if(data.stage){$('#engine-state span').textContent=data.stage;return;}
  if(data.fatal){$('#engine-state').className='engine-pill error';$('#engine-state span').textContent='载入失败 · 点击重试';toast('数学引擎加载失败，请点击右上角重试。');return;}
  if(data.ready){state.ready=true;state.catalog=data.catalog;$('#engine-state').className='engine-pill ready';$('#engine-state span').textContent='符号引擎已就绪 · 本地计算';$('#editor-note').textContent='不需要 API Key';$('#rule-total').textContent=state.catalog.ruleCount+' 条';renderExamples();renderRules();setBusy(false);if(!state.example)loadExample(state.catalog.examples[0],false);verify();return;}
  const p=pending.get(data.id);if(!p)return;if(data.progress){p.progress?.(data.progress);return;}clearTimeout(p.timeout);pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data.result);
 };
 worker.onerror=()=>{$('#engine-state').className='engine-pill error';$('#engine-state span').textContent='引擎不可用 · 点击重试';};
}
$('#engine-state').onclick=()=>{if(!state.ready)startWorker();};
function renderExamples(){if(!state.catalog)return;$('#side-examples').innerHTML=state.catalog.examples.map(e=>`<button class="example ${state.example?.id===e.id?'active':''}" data-example="${esc(e.id)}">${esc(e.title)}<small>${esc(e.category)}</small></button>`).join('');$$('[data-example]').forEach(b=>b.onclick=()=>loadExample(state.catalog.examples.find(e=>e.id===b.dataset.example)));$('#mobile-example').innerHTML=state.catalog.examples.map(e=>`<option value="${esc(e.id)}" ${state.example?.id===e.id?'selected':''}>${esc(e.category)} · ${esc(e.title)}</option>`).join('');$('#mobile-example').onchange=e=>loadExample(state.catalog.examples.find(x=>x.id===e.target.value));}
function steps(){return $$('#step-editors textarea').map(x=>x.value.trim());}
function setSteps(lines){$('#step-editors').innerHTML=lines.map((line,i)=>`<label class="editor-row"><span>E<sub>${i+1}</sub></span><textarea aria-label="第${i+1}行推导" spellcheck="false" rows="2">${esc(line)}</textarea><button class="remove-step" data-remove="${i}" aria-label="删除第${i+1}行" title="删除本行">×</button></label>`).join('');$$('#step-editors textarea').forEach(e=>e.oninput=markDirty);$$('[data-remove]').forEach(b=>b.onclick=e=>{e.preventDefault();if(steps().length<=2)return toast('推导至少保留两行。');setSteps(steps().filter((_,i)=>i!==Number(b.dataset.remove)));markDirty();});}
function markDirty(){if(!state.dirty&&state.result)toast('推导已修改，请重新验证。');state.dirty=true;$('#path-stat').textContent='已修改 · 等待复核';$('#export-btn').disabled=true;$$('.editor-row').forEach(e=>e.classList.remove('is-error','selected'));if(state.result){$('#diagnosis-content').innerHTML='<div class="standby-visual"><div class="proof-mark">ƒ</div><h3>推导已修改</h3><p>旧结论已失效。点击「验证推导」获取最新证据。</p></div>';$('#path-content').innerHTML='<div class="empty-hint"><p>当前输入尚未验证。</p></div>';$('#ast-content').textContent='重新验证后更新表达式树。';}}
function loadExample(e,run=true){if(state.busy)return toast('当前计算尚未结束，请稍候。');state.example=structuredClone(e);state.result=null;state.dirty=false;state.selected=0;setSteps(e.steps);$('#context-input').value=JSON.stringify(e.context||{},null,2);$('#example-category').textContent=e.category;$('#example-title').textContent=e.title;$('#example-description').textContent=e.description||'修改表达式后重新验证，检查各步的规则依据。';updateContextSummary();renderExamples();switchView('verify');plot();$('#export-btn').disabled=true;$('#path-content').innerHTML='<div class="empty-hint"><span class="empty-symbol">∴</span><p>点击验证，检查本条推导。</p></div>';if(run&&state.ready)verify();}
function context(){let c;try{c=JSON.parse($('#context-input').value);}catch(e){throw Error('条件 JSON 格式不正确，请检查引号、逗号和括号。');}if(!c||typeof c!=='object'||Array.isArray(c))throw Error('条件应为 JSON 对象。');return c;}
function updateContextSummary(){try{const c=context();$('#context-summary').textContent=Object.keys(c.definitions||{}).length?'已声明 '+Object.keys(c.definitions).length+' 个变换对':Object.keys(c.initial||{}).length?'初值 '+Object.entries(c.initial).map(([k,v])=>k+'='+v).join('，'):c.causal?'已声明因果信号':'未添加额外条件';}catch(e){$('#context-summary').textContent='请检查格式';}}
$('#context-input').oninput=()=>{markDirty();updateContextSummary();};$('#add-step').onclick=()=>{const all=steps();if(all.length>=16)return toast('最多支持16行，请拆分推导。');setSteps([...all,'']);markDirty();$$('#step-editors textarea').at(-1).focus();};$('#reset-btn').onclick=()=>{if(state.example)loadExample(state.example);};$('#verify-btn').onclick=()=>verify();
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(!state.busy)verify();}});
async function verify(){if(state.busy)return;try{const c=context(),lines=steps();if(lines.some(x=>!x))throw Error('请填写每一行表达式，或删除空白行。');state.dirty=false;setBusy(true);$('#path-stat').textContent='解析与规则匹配中';const r=await request({action:'verify',steps:lines,context:c});if(r.error||r.status==='error')throw Error(r.summary||r.error);if(JSON.stringify(steps())!==JSON.stringify(lines)||JSON.stringify(context())!==JSON.stringify(c)){markDirty();return;}state.result=r;state.snapshot={steps:lines,context:c};state.selected=r.firstError?r.firstError-2:Math.max(0,r.steps.findIndex(x=>x.status!=='correct'));$('#path-stat').textContent=r.steps.length+' 次变形 · '+(r.elapsedMs/1000).toFixed(2)+' s';$('#export-btn').disabled=false;renderResult();}catch(e){toast(e.message);$('#path-stat').textContent='本次未完成';$('#diagnosis-content').innerHTML=`<div class="result-banner unknown"><div class="result-kicker">INPUT CHECK</div><h3>请检查输入</h3><p>${esc(e.message)}</p></div><div class="result-body"><p>语法或条件格式问题不属于数学错误，修正输入后可重新验证。</p></div>`;}finally{setBusy(false);}}
function renderResult(){const r=state.result;if(!r)return;$$('.editor-row').forEach((e,i)=>{e.classList.toggle('is-error',i===r.firstError-1);e.classList.toggle('selected',i===state.selected+1);});$('#path-content').innerHTML=r.steps.map((row,i)=>`<div class="path-row ${i===state.selected?'selected':''}" tabindex="0" role="button" data-path="${i}"><span class="path-icon ${row.status}">${{correct:'✓',wrong:'×',incomplete:'!',unknown:'?'}[row.status]||'?'}</span><div><h4>第 ${row.line-1} 行 <span class="minor">→</span> 第 ${row.line} 行</h4><p>${esc(row.ruleNames.join(' · ')||'符号与条件核验')}</p></div><span class="path-label ${row.status==='wrong'?'red':row.status==='correct'?'green':'amber'}">${esc(row.statusLabel)}</span></div>`).join('');$$('[data-path]').forEach(b=>{const go=()=>{state.selected=Number(b.dataset.path);renderResult();};b.onclick=go;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});renderDiagnosis(r.steps[state.selected]);$('#ast-content').innerHTML=r.ast.map((a,i)=>`<details ${i===state.selected+1?'open':''}><summary>E${i+1} · ${esc(r.normalized[i])}</summary><pre>${esc(a)}</pre></details>`).join('');plot();}
function renderDiagnosis(row){
 const r=state.result,title=row.status==='wrong'?`第 ${row.line} 行，${row.line===r.firstError?(r.firstErrorCertain?'首个错误':'最早已确认错误'):'当前步不成立'}`:row.inherited?'局部正确，仍继承前错':row.status==='correct'?'这一步，已验证正确':row.status==='incomplete'?'表达式正确，还缺收敛域':'条件不足，保留判断';
 const note=row.inherited?'局部等价不能修复之前的错误。请先返回最早出错的一步。':row.status==='wrong'?'错误位置已定位；后续推导需要从这里重新检查。':row.status==='correct'?(r.status==='correct'?'整条推导的相邻步骤均已通过。':'此结论仅适用于当前选中的相邻步骤。'):'系统不会把未完成的证明标记为正确。';
 $('#diagnosis-content').innerHTML=`<div class="result-banner ${row.status}"><div class="result-kicker"><span>${{wrong:'FIRST DIVERGENCE',correct:'VERIFIED STEP',unknown:'UNRESOLVED',incomplete:'MISSING CONDITION'}[row.status]||'CHECK'}</span><span>${row.line-1} / ${r.steps.length} 次变形</span></div><h3>${title}</h3><p>${note}</p></div><div class="result-body"><div class="rule-reference"><span class="rule-id">${esc(row.ruleIds.join(' + ')||'—')}</span><strong>${esc(row.ruleNames.join(' · ')||'有界验证')}</strong></div><p>${esc(row.explanation)}</p><div class="comparison"><div class="formula-box ${row.status==='wrong'?'current':''}"><label>当前结果 · E${row.line}</label><div class="formula">${math(row.afterLatex||(r.latex||[])[row.line-1],row.after)}</div></div>${row.expected&&row.status!=='correct'?`<div class="formula-box expected"><label>${row.status==='unknown'?'条件成立时的候选':'规则对应结果'}</label><div class="formula">${math(row.expectedLatex,row.expected)}</div>${row.expected.includes('ROC:')?`<p class="minor">${esc(row.expected.split(';')[1]||'')}</p>`:''}</div>`:''}</div>${row.diff?.path?`<div class="diff-line"><span>局部差异</span><code>${esc(row.diff.before)}</code><span>→</span><code class="fixed">${esc(row.diff.after)}</code></div>`:''}<div class="evidence-tags">${[...row.evidence,...row.conditions].map(t=>`<span>${esc(t)}</span>`).join('')}</div>${row.trace?.length?`<details class="trace-details"><summary>展开 ${row.trace.length} 次规则重写</summary>${row.trace.map(q=>`<div class="trace-step"><span class="rule-id">${esc(q.ruleId)}</span><code>${esc(q.before)}</code><code>→ ${esc(q.after)}</code></div>`).join('')}</details>`:''}${row.samples?.length?`<details class="trace-details"><summary>查看数值反例</summary>${row.samples.map(q=>`<div class="trace-step">${esc(q.at)}<code>候选：${esc(q.expected)}</code><code>当前：${esc(q.actual)}</code><span>绝对差：${Number(q.error).toPrecision(5)}</span></div>`).join('')}</details>`:''}${row.expected&&['wrong','incomplete'].includes(row.status)?`<div class="repair-row"><span>只替换当前错误行<br>随后重新检查整条推导</span><button class="button primary compact repair-button" id="repair-btn">应用建议并复核</button></div>`:''}</div>`;
 if($('#repair-btn'))$('#repair-btn').onclick=async()=>{const all=steps();all[row.line-1]=row.expected;setSteps(all);toast('已修改第 '+row.line+' 行，正在复核后续步骤。');await verify();};
}
function plot(){
 const row=state.result?.steps[state.selected],ids=row?.ruleIds||[],type=state.example?.category||'傅里叶';let svg='',caption='',legend='',label='时移 · 教学示意';
 const axis='<path d="M26 132H443M80 20V145" stroke="#dbe5e8" fill="none"/><text x="74" y="158" fill="#90a3ad" font-size="11">0</text><text x="435" y="157" fill="#90a3ad" font-size="11">t</text>';
 const curve=(shift,scale=1)=>{let d='';for(let i=0;i<=400;i++){const tt=(i-55)/42,v=tt>=shift?Math.exp(-(tt-shift)*scale):0;d+=(i?'L':'M')+(26+i)+','+(132-82*v).toFixed(2);}return d;};
 if(type==='Z变换'){label='收敛域 · 教学示意';svg='<rect x="35" y="10" width="390" height="150" rx="7" fill="#e9f5f0"/><circle cx="230" cy="85" r="48" fill="white" stroke="#45a287" stroke-dasharray="4 4"/><path d="M50 85H411M230 20V150" stroke="#bbd5ce"/><circle cx="278" cy="85" r="3" fill="#d28174"/><text x="292" y="79" fill="#a87369" font-size="11">极点 a</text><text x="337" y="40" fill="#6e998d" font-size="11">|z| &gt; |a|</text><text x="202" y="105" fill="#8f9fa6" font-size="11">不收敛</text><text x="375" y="106" fill="#91a2a9" font-size="11">Re(z)</text>';caption='右边指数序列 aⁿu[n] 的 ROC 位于极点半径之外。左边序列对应内部区域；同一个有理式不能唯一确定序列。图中圆周不属于 ROC。';
 }else if(type==='拉普拉斯'){label='初值项 · 教学示意';svg=axis+'<path d="'+curve(0)+'" stroke="#218e78" stroke-width="2.5" fill="none"/><circle cx="81" cy="50" r="4" fill="#da8374"/><path d="M42 50H117" stroke="#da8374" stroke-dasharray="4 4"/><text x="118" y="45" fill="#b7796d" font-size="12">x(0⁻)</text>';caption='从 0⁻ 开始的单边拉普拉斯变换保留边界初值：L{x′} = sX − x(0⁻)。图形仅解释初值所在位置，不代表输入信号的实际波形。';
 }else if(ids.includes('F04')||state.example?.id==='ft-scale'){label='尺度系数 · 教学示意';svg=axis+`<path d="${curve(0)}" stroke="#268e79" stroke-width="2.5" fill="none"/><path d="${curve(0,2)}" stroke="#cf8177" stroke-width="2" stroke-dasharray="5 4" fill="none"/>`;legend='<div class="chart-legend"><span>x(t)</span><span>x(2t)</span></div>';caption='时间压缩改变频谱宽度，也引入 1/|a| 的幅度系数。图中展示正尺度压缩；负尺度还会反转时间方向。';
 }else{svg=axis+`<path d="${curve(0)}" stroke="#268e79" stroke-width="2.5" fill="none"/><path d="${curve(2)}" stroke="#d38176" stroke-width="2" stroke-dasharray="5 4" fill="none"/><text x="157" y="158" fill="#91a4ad" font-size="11">2</text><path d="M86 27H160" stroke="#b4d3c9"/><text x="110" y="20" fill="#6e9d8b" font-size="10">延迟 2</text>`;legend='<div class="chart-legend"><span>原信号 x(t)</span><span>延迟 x(t − 2)</span></div>';caption='以因果指数信号为例：时域向右平移 2，对应频域乘 e⁻ʲ²ω。此图是时移性质的教学示意，规则证据决定当前输入是否成立。';}
 $('#plot-label').textContent=label;$('#plot-content').innerHTML=`<svg class="signal-chart" viewBox="0 0 460 170" role="img" aria-label="${esc(label)}">${svg}</svg>${legend}<p class="plot-caption">${caption}</p>`;
}
function renderRules(){if(!state.catalog)return;const term=$('#rule-search').value.toLowerCase();const rules=state.catalog.rules.filter(r=>(state.ruleCategory==='全部'||r.category===state.ruleCategory)&&[r.name,r.id,r.formula,r.conditions].join(' ').toLowerCase().includes(term));$('#rules-grid').innerHTML=rules.length?rules.map(r=>`<article class="rule-card"><div class="rule-card-head"><span class="category">${esc(r.category)}</span><span class="rule-id">${esc(r.id)}</span></div><h3>${esc(r.name)}</h3><div class="rule-formula">${esc(r.formula)}</div><p>适用条件：${esc(r.conditions)}</p><button data-rule="${esc(r.id)}">载入此规则的示例</button></article>`).join(''):'<div class="empty-hint">没有匹配的规则，请尝试其他关键词。</div>';$$('[data-rule]').forEach(b=>b.onclick=()=>{const r=state.catalog.rules.find(r=>r.id===b.dataset.rule);loadExample({id:'rule-'+r.id,title:r.name,category:r.category,description:r.conditions,steps:[r.exampleBefore,r.exampleAfter],context:r.exampleContext||((r.id==='L06'||r.id==='L07')?{causal:true}:{})});});}
$('#rule-search').oninput=renderRules;$$('[data-cat]').forEach(b=>b.onclick=()=>{state.ruleCategory=b.dataset.cat;$$('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));renderRules();});
function renderTestRows(){const rows=state.testResults.filter(r=>state.testFilter!=='failed'||!r.passed);$('#test-body').innerHTML=rows.length?rows.map(r=>`<tr><td><button data-test="${esc(r.id)}">${esc(r.title)}</button><small>${esc(r.id)} · ${esc(r.category)}</small></td><td><span class="badge ${r.expected}">${labels[r.expected]||r.expected}</span></td><td><span class="badge ${r.actual}">${labels[r.actual]||r.actual}</span></td><td>${r.actualFirstError?'第 '+r.actualFirstError+' 行':'—'}${r.actualFirstError!==r.expectedFirstError?'<small>预期 '+r.expectedFirstError+'</small>':''}</td><td class="${r.passed?'green':'red'}">${r.passed?'✓ 通过':'× 失败'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-table">'+(state.testFilter==='failed'&&state.testResults.length?'当前没有失败样本。':'运行后显示真实测试结果。')+'</td></tr>';$$('[data-test]').forEach(b=>b.onclick=()=>{const test=state.testResults.find(r=>r.id===b.dataset.test);loadExample({...test,description:'验收集固定样本 · 预期 '+labels[test.expected]});});}
$$('[data-test-filter]').forEach(b=>b.onclick=()=>{state.testFilter=b.dataset.testFilter;$$('[data-test-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTestRows();});
$('#run-tests').onclick=async()=>{if(state.busy)return;state.testResults=[];state.testReport=null;$('#export-tests').disabled=true;setBusy(true);$('#run-tests').textContent='正在逐条核验…';$('#test-time').textContent='';try{const result=await request({action:'tests'},p=>{state.testResults.push(p.row);$('#test-progress').textContent=`已核验 ${p.done} / ${p.total} 条`;$('#test-progress-fill').style.width=p.done/p.total*100+'%';$('#test-passed').textContent=state.testResults.filter(x=>x.passed).length;renderTestRows();});state.testReport=result;state.testResults=result.results;const wrong=result.results.filter(r=>r.expected==='wrong'),located=wrong.filter(r=>r.actualFirstError===r.expectedFirstError&&r.actual==='wrong').length;$('#test-localization').textContent=located+'/'+wrong.length;$('#test-time').textContent=(result.elapsedMs/1000).toFixed(1)+' s';$('#test-progress').textContent=`完成 · ${result.passed} 通过 / ${result.failed} 失败`;$('#export-tests').disabled=false;renderTestRows();toast('验收完成：'+result.passed+'/'+result.total+' 通过。');}catch(e){toast(e.message);$('#test-progress').textContent='测试中断，已保留完成的记录。';}finally{setBusy(false);$('#run-tests').textContent='▶ 重新运行验收测试';}};
function download(name,content,type='application/json'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-tests').onclick=()=>{if(state.testReport)download('SignalProof-test-results.json',JSON.stringify(state.testReport,null,2));};
$('#export-btn').onclick=()=>{if(!state.result||state.dirty)return toast('请先验证当前推导。');const r=state.result,body=`<!doctype html><html lang="zh"><meta charset="utf-8"><title>SignalProof 验证报告</title><style>body{font:16px/1.8 'Segoe UI','Microsoft YaHei',sans-serif;color:#213e49;max-width:900px;margin:50px auto;padding:20px}h1{color:#0c7d70}section{border:1px solid #dce6e8;padding:20px;margin:20px 0;border-radius:10px}pre{white-space:pre-wrap;background:#f5f8f9;padding:15px}small{color:#82939b}</style><h1>SignalProof · 推导验证报告</h1><p>${esc(r.summary)}</p><small>${new Date().toLocaleString('zh-CN')} · Fourier 角频率 / Laplace 单边 0⁻ / Z 双边</small><h2>输入与条件</h2><pre>${esc(state.snapshot.steps.map((s,i)=>`E${i+1}: ${s}`).join('\n'))}</pre><pre>${esc(JSON.stringify(state.snapshot.context,null,2))}</pre>${r.steps.map(row=>`<section><h2>第 ${row.line-1} → ${row.line} 行 · ${esc(row.statusLabel)}</h2><p>${esc(row.explanation)}</p><pre>${esc(row.before)}\n→ ${esc(row.after)}</pre><p>规则：${esc(row.ruleIds.join(', '))}</p><p>建议结果：${esc(row.expected||'—')}</p><p>证据：${esc(row.evidence.join('；'))}</p><p>条件：${esc(row.conditions.join('；'))}</p></section>`).join('')}<p>数值抽样通过不等于数学证明；最小错因是相对正确候选的局部结构解释，并不承诺唯一。</p></html>`;download('SignalProof-verification-report.html',body,'text/html;charset=utf-8');toast('已导出可打印的 HTML 验证报告。');};
if(document.modelContext?.registerTool){const lifecycle=new AbortController();Promise.resolve(document.modelContext.registerTool({name:'verify_signal_derivation',title:'核验信号推导',description:'将推导载入当前工作区并用符号引擎验证，更新可见证据。',inputSchema:{type:'object',properties:{steps:{type:'array',items:{type:'string'},minItems:2,maxItems:16},context:{type:'object'}},required:['steps'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input)=>{if(!Array.isArray(input.steps)||input.steps.length<2||input.steps.length>16||input.steps.some(s=>typeof s!=='string'||s.length>1200))throw Error('无效推导步骤');if(state.busy||!state.ready)throw Error('数学引擎忙碌或尚未就绪');loadExample({id:'agent',title:'自定义推导',category:'傅里叶',steps:input.steps,context:input.context||{}},false);await verify();if(!state.result)throw Error('输入未通过验证');return{status:state.result.status,firstError:state.result.firstError,summary:state.result.summary};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
setSteps(steps());plot();switchView(location.hash.slice(1)||'verify');startWorker();
