'use strict';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={catalog:null,example:null,result:null,selected:0,dirty:false,busy:false,ready:false,ruleCategory:'全部',testResults:[],testFilter:'all',testReport:null,examples:[],caseCategory:'全部',view:'verify'};
const labels={correct:'已验证正确',wrong:'已确认错误',unknown:'暂无法判断',incomplete:'缺少收敛域',error:'输入错误'};
let worker,sequence=0;const pending=new Map();
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function math(tex,fallback,display=true){if(tex&&window.katex){try{return katex.renderToString(tex,{displayMode:display,throwOnError:true,strict:false,trust:false,output:'htmlAndMathml'});}catch(e){}}return esc(fallback??tex??'');}
function formula(tex,fallback,roc=''){return `<div class="formula math-scroll">${math(tex,fallback)}</div>${roc?`<div class="formula-roc"><span>ROC</span><div class="math-scroll">${math(roc,roc,false)}</div></div>`:''}`;}
let ruleLatex={};fetch('data/rule-latex.json?v=3').then(r=>r.ok?r.json():{}).then(data=>{ruleLatex=data;renderRules();}).catch(()=>{});
function renderStaticMath(){$$('[data-math]').forEach(e=>{e.innerHTML=math(e.dataset.math,e.textContent,e.dataset.inline!=='true');});}
let previewTimer,previewRunning=false,previewKey='';
function queueFormulaPreview(){
 const lines=steps(),key=JSON.stringify(lines);if(key===previewKey&&state.preview)return;
 clearTimeout(previewTimer);state.preview=null;$('#copy-latex').disabled=true;
 $$('.editor-preview').forEach((e,i)=>{e.innerHTML=`<span class="preview-note">${!lines[i]?'填写表达式后显示公式':state.ready?'正在排版…':'数学引擎就绪后显示公式预览'}</span>`;});
 if(!state.ready||state.busy||previewRunning)return;
 previewTimer=setTimeout(async()=>{previewRunning=true;try{const r=await request({action:'format',steps:lines});if(key!==JSON.stringify(steps()))return;state.preview=r.lines;previewKey=key;$$('.editor-preview').forEach((e,i)=>{const row=r.lines[i];e.innerHTML=row?.error?`<span class="preview-note">${esc(row.error)}</span>`:formula(row?.latex,lines[i],row?.rocLatex);});$('#copy-latex').disabled=!r.lines.length||r.lines.some(x=>x.error);}catch(e){$$('.editor-preview').forEach(x=>{x.innerHTML='<span class="preview-note">暂未生成预览，请检查输入或等待引擎就绪。</span>';});}finally{previewRunning=false;if(key!==JSON.stringify(steps()))queueFormulaPreview();}},320);
}
function switchView(view){if(!['verify','cases','rules','tests','guide'].includes(view))view='verify';state.view=view;$$('.view').forEach(e=>e.classList.toggle('active',e.id===view+'-view'));$$('.nav').forEach(e=>{e.classList.toggle('active',e.dataset.view===view);e.setAttribute('aria-current',e.dataset.view===view?'page':'false');});$('#page-crumb').textContent={verify:'推导验证',cases:'案例广场',rules:'规则图谱',tests:'验收测试',guide:'使用与约定'}[view];if(location.hash!=='#'+view)history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'smooth'});}
$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));window.addEventListener('hashchange',()=>switchView(location.hash.slice(1)));
function setBusy(v){state.busy=v;$('#verify-btn').disabled=v||!state.ready;$('#run-tests').disabled=v||!state.ready;$('#verify-btn').classList.toggle('busy',v);$('#verify-btn').innerHTML=v?'正在符号验证…':'<span>▶</span> 验证推导';$$('.repair-button').forEach(x=>x.disabled=v);if(state.example)renderLearning();if(!v)queueFormulaPreview();}
function request(payload,progress){return new Promise((resolve,reject)=>{if(!state.ready)return reject(Error('数学引擎尚未就绪，请稍候。'));const id=++sequence;const timeout=setTimeout(()=>{pending.delete(id);worker.terminate();state.ready=false;$('#engine-state').className='engine-pill error';$('#engine-state span').textContent='计算超时 · 点击重启';setBusy(false);reject(Error('计算超出时间上限。请拆分步骤，并点击右上角重启引擎。'));},payload.action==='tests'?300000:35000);pending.set(id,{resolve,reject,timeout,progress});worker.postMessage({id,request:payload});});}
function startWorker(){
 if(worker)worker.terminate();state.ready=false;$('#engine-state').className='engine-pill';$('#engine-state span').textContent='正在载入数学引擎';worker=new Worker('worker.js?v=3');
 worker.onmessage=({data})=>{
  if(data.stage){$('#engine-state span').textContent=data.stage;return;}
  if(data.fatal){$('#engine-state').className='engine-pill error';$('#engine-state span').textContent='载入失败 · 点击重试';toast('数学引擎加载失败，请点击右上角重试。');return;}
  if(data.ready){state.ready=true;state.catalog=data.catalog;$('#engine-state').className='engine-pill ready';$('#engine-state span').textContent='符号引擎已就绪 · 本地计算';$('#editor-note').textContent='不需要 API Key';$('#rule-total').textContent=state.catalog.ruleCount+' 条';renderRules();setBusy(false);examplesReady.then(()=>{if(!state.examples.length){state.examples=state.catalog.examples;renderExamples();renderCases();}initializeExample();});return;}
  const p=pending.get(data.id);if(!p)return;if(data.progress){p.progress?.(data.progress);return;}clearTimeout(p.timeout);pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data.result);
 };
 worker.onerror=()=>{$('#engine-state').className='engine-pill error';$('#engine-state span').textContent='引擎不可用 · 点击重试';};
}
$('#engine-state').onclick=()=>{if(!state.ready)startWorker();};
const requestedCase=new URLSearchParams(location.search).get('case');
const examplesReady=fetch('data/examples.json').then(r=>{if(!r.ok)throw Error('案例载入失败');return r.json();}).then(data=>{if(!Array.isArray(data)||!data.length||data.some(e=>!e.id||!Array.isArray(e.steps)||e.steps.length<2))throw Error('案例格式有误');state.examples=data;renderExamples();renderCases();initializeExample();}).catch(()=>{$('#case-results-count').textContent='案例库暂不可用；引擎就绪后将载入内置案例。';});
function initializeExample(){if(state.example||!state.examples.length)return;const chosen=state.examples.find(e=>e.id===requestedCase)||state.examples[0];loadExample(chosen,false,{preserveView:true});if(requestedCase&&!state.examples.some(e=>e.id===requestedCase))toast('未找到链接中的案例，已载入第一道题。');}
function renderExamples(){
 const picks=['ft-shift','lt-initial','z-roc','conv'].map(id=>state.examples.find(e=>e.id===id)).filter(Boolean);const featured=picks.length?picks:state.examples.slice(0,4);
 $('#side-examples').innerHTML=featured.map(e=>`<button class="example ${state.example?.id===e.id?'active':''}" data-example="${esc(e.id)}">${esc(e.title)}<small>${esc(e.category)} · ${esc(e.difficulty||'基础')}</small></button>`).join('');
 $$('#side-examples [data-example]').forEach(b=>b.onclick=()=>loadExample(state.examples.find(e=>e.id===b.dataset.example),false));
 $('#mobile-example').innerHTML=(state.example&&!state.examples.some(e=>e.id===state.example.id)?`<option value="" selected disabled>${esc(state.example.title)} · 自定义示例</option>`:'')+state.examples.map(e=>`<option value="${esc(e.id)}" ${state.example?.id===e.id?'selected':''}>${esc(e.category)} · ${esc(e.title)}</option>`).join('');$('#mobile-example').onchange=e=>loadExample(state.examples.find(x=>x.id===e.target.value),false);$('#case-total').textContent=state.examples.length;
}
function caseIcon(category){const paths={卷积:'M5 48V23H39V48M30 48V11H64V48M75 48L92 10L109 48',傅里叶:'M3 30C10 2 18 2 25 30S40 58 47 30S62 2 69 30S84 58 91 30S106 2 113 30',拉普拉斯:'M4 50H113M15 52V5M17 9C30 13 30 36 47 41S79 48 112 48',Z变换:'M5 30H109M57 3V57M82 30A25 25 0 1 0 32 30A25 25 0 1 0 82 30M69 26L77 34M69 34L77 26'};return `<svg viewBox="0 0 118 60" aria-hidden="true"><path d="${paths[category]||paths.傅里叶}"/></svg>`;}
function renderCases(){const term=$('#case-search').value.trim().toLowerCase(),difficulty=$('#case-difficulty').value,kind=$('#case-kind').value;const rows=state.examples.filter(e=>(state.caseCategory==='全部'||e.category===state.caseCategory)&&(difficulty==='全部'||e.difficulty===difficulty)&&(kind==='全部'||e.kind===kind)&&[e.title,e.task,e.description,e.concept,e.category].join(' ').toLowerCase().includes(term));$('#case-results-count').textContent=`找到 ${rows.length} / ${state.examples.length} 道案例`;$('#cases-grid').innerHTML=rows.length?rows.map(e=>`<article class="case-card" data-category="${esc(e.category)}"><div class="case-card-visual">${caseIcon(e.category)}<span class="case-card-number">${String(state.examples.indexOf(e)+1).padStart(2,'0')}</span></div><div class="case-card-body"><div class="case-card-tags"><span class="category">${esc(e.category)}</span><span>${esc(e.difficulty||'基础')}</span><span>${esc(e.kind||'教学案例')}</span></div><h2>${esc(e.title)}</h2><p class="case-card-task">${esc(e.task||e.description)}</p><p class="case-card-concept">知识点 · ${esc(Array.isArray(e.concept)?e.concept.join(' / '):e.concept||'相邻步骤等价性')}</p><div class="case-card-footer"><span>${e.steps.length} 行推导 · 可编辑验证</span><button data-load-case="${esc(e.id)}" aria-label="载入案例：${esc(e.title)}">载入并探索 <span aria-hidden="true">↗</span></button></div></div></article>`).join(''):'<div class="empty-hint">没有符合条件的案例。试试减少筛选条件或更换关键词。</div>';
 $$('[data-load-case]').forEach(b=>b.onclick=()=>{loadExample(state.examples.find(e=>e.id===b.dataset.loadCase),false);$('#example-title').focus({preventScroll:true});});
}
$$('[data-case-category]').forEach(b=>b.onclick=()=>{state.caseCategory=b.dataset.caseCategory;$$('[data-case-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderCases();});
$('#case-search').oninput=renderCases;$('#case-difficulty').onchange=renderCases;$('#case-kind').onchange=renderCases;$('#clear-case-filters').onclick=()=>{state.caseCategory='全部';$('#case-search').value='';$('#case-difficulty').value='全部';$('#case-kind').value='全部';$$('[data-case-category]').forEach(x=>{x.classList.toggle('active',x.dataset.caseCategory==='全部');x.setAttribute('aria-pressed',String(x.dataset.caseCategory==='全部'));});renderCases();};
function renderLearning(){const e=state.example;if(!e)return;$('#learning-task').textContent=e.task||'判断相邻两行是否等价，查看规则依据与适用条件。';$('#learning-tags').innerHTML=[e.difficulty,e.kind].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');$('#learning-hint-text').textContent=e.hint||'先确认变换约定，再检查系数、符号与适用条件。';const takeaway=$('#learning-takeaway');takeaway.hidden=!state.result||state.dirty;takeaway.innerHTML=state.result&&!state.dirty?`<strong>本题复盘</strong><p>${esc(e.takeaway||'结合当前结论，逐项核对规则的适用条件。局部等价不代表整条推导没有前错。')}</p>`:'';const i=state.examples.findIndex(x=>x.id===e.id);$('#case-position').textContent=i<0?'自定义 / 规则示例':`${i+1} / ${state.examples.length} 道案例`;$('#previous-case').disabled=i<=0||state.busy;$('#next-case').disabled=i<0||i>=state.examples.length-1||state.busy;}
function moveCase(delta){const i=state.examples.findIndex(e=>e.id===state.example?.id),e=state.examples[i+delta];if(e)loadExample(e,false);}
$('#previous-case').onclick=()=>moveCase(-1);$('#next-case').onclick=()=>moveCase(1);

function steps(){return $$('#step-editors textarea').map(x=>x.value.trim());}
function setSteps(lines){state.preview=null;$('#step-editors').innerHTML=lines.map((line,i)=>`<div class="editor-row"><span class="equation-number">E<sub>${i+1}</sub></span><div class="equation-editor"><label for="expression-${i}">输入表达式</label><textarea id="expression-${i}" aria-label="第${i+1}行推导" spellcheck="false" rows="1">${esc(line)}</textarea><div class="editor-preview" aria-label="第${i+1}行公式预览"></div></div><button class="remove-step" data-remove="${i}" aria-label="删除第${i+1}行" title="删除本行">×</button></div>`).join('');$$('#step-editors textarea').forEach(e=>e.oninput=markDirty);$$('[data-remove]').forEach(b=>b.onclick=e=>{e.preventDefault();if(steps().length<=2)return toast('推导至少保留两行。');setSteps(steps().filter((_,i)=>i!==Number(b.dataset.remove)));markDirty();});queueFormulaPreview();}
function markDirty(){queueFormulaPreview();if(!state.dirty&&state.result)toast('推导已修改，请重新验证。');state.dirty=true;renderLearning();$('#path-stat').textContent='已修改 · 等待复核';$('#export-btn').disabled=true;$$('.editor-row').forEach(e=>e.classList.remove('is-error','selected'));if(state.result){$('#diagnosis-content').innerHTML='<div class="standby-visual"><div class="proof-mark">ƒ</div><h3>推导已修改</h3><p>旧结论已失效。点击「验证推导」获取最新证据。</p></div>';$('#path-content').innerHTML='<div class="empty-hint"><p>当前输入尚未验证。</p></div>';$('#ast-content').textContent='重新验证后更新表达式树。';}}
function loadExample(e,run=true,options={}){if(!e)return;if(state.busy)return toast('当前计算尚未结束，请稍候。');state.example=structuredClone(e);state.result=null;state.dirty=false;state.selected=0;setSteps(e.steps);$('#context-input').value=JSON.stringify(e.context||{},null,2);$('#example-category').textContent=e.category;$('#example-title').textContent=e.title;$('#example-title').tabIndex=-1;$('#example-description').textContent=e.description||'修改表达式后重新验证，检查各步的规则依据。';$('#learning-hint').open=false;updateContextSummary();renderExamples();renderLearning();if(!options.preserveView)switchView('verify');{const url=new URL(location.href);if(state.examples.some(x=>x.id===e.id))url.searchParams.set('case',e.id);else url.searchParams.delete('case');history.replaceState(null,'',url.pathname+url.search+url.hash);}plot();$('#export-btn').disabled=true;$('#path-stat').textContent='等待验证';$('#ast-content').textContent='验证后显示原始表达式树。';$('#diagnosis-content').innerHTML='<div class="standby-visual"><div class="proof-mark">ƒ<span>?</span></div><h3>先做一次自己的判断</h3><p>阅读题意，检查每一行变形。<br>点击「验证推导」后，展开对应的规则证据。</p></div><div class="capability-row"><span>首错定位</span><span>条件检查</span><span>修正复核</span></div>';$('#path-content').innerHTML='<div class="empty-hint"><span class="empty-symbol">∴</span><p>准备好了，就验证这条推导。</p><small>可先展开提示，也可以直接修改公式。</small></div>';if(run&&state.ready)verify();}
function context(){let c;try{c=JSON.parse($('#context-input').value);}catch(e){throw Error('条件 JSON 格式不正确，请检查引号、逗号和括号。');}if(!c||typeof c!=='object'||Array.isArray(c))throw Error('条件应为 JSON 对象。');return c;}
function updateContextSummary(){try{const c=context();$('#context-summary').textContent=Object.keys(c.definitions||{}).length?'已声明 '+Object.keys(c.definitions).length+' 个变换对':Object.keys(c.initial||{}).length?'初值 '+Object.entries(c.initial).map(([k,v])=>k+'='+v).join('，'):c.causal?'已声明因果信号':'未添加额外条件';}catch(e){$('#context-summary').textContent='请检查格式';}}
$('#context-input').oninput=()=>{markDirty();updateContextSummary();};$('#add-step').onclick=()=>{const all=steps();if(all.length>=16)return toast('最多支持16行，请拆分推导。');setSteps([...all,'']);markDirty();$$('#step-editors textarea').at(-1).focus();};$('#reset-btn').onclick=()=>{if(state.example)loadExample(state.example);};$('#verify-btn').onclick=()=>verify();
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(!state.busy)verify();}});
async function verify(){if(state.busy)return;try{const c=context(),lines=steps();if(lines.some(x=>!x))throw Error('请填写每一行表达式，或删除空白行。');state.dirty=false;setBusy(true);$('#path-stat').textContent='解析与规则匹配中';const r=await request({action:'verify',steps:lines,context:c});if(r.error||r.status==='error')throw Error(r.summary||r.error);if(JSON.stringify(steps())!==JSON.stringify(lines)||JSON.stringify(context())!==JSON.stringify(c)){markDirty();return;}state.result=r;state.snapshot={steps:lines,context:c};state.selected=r.firstError?r.firstError-2:Math.max(0,r.steps.findIndex(x=>x.status!=='correct'));$('#path-stat').textContent=r.steps.length+' 次变形 · '+(r.elapsedMs/1000).toFixed(2)+' s';$('#export-btn').disabled=false;renderResult();}catch(e){toast(e.message);$('#path-stat').textContent='本次未完成';$('#diagnosis-content').innerHTML=`<div class="result-banner unknown"><div class="result-kicker">INPUT CHECK</div><h3>请检查输入</h3><p>${esc(e.message)}</p></div><div class="result-body"><p>语法或条件格式问题不属于数学错误，修正输入后可重新验证。</p></div>`;}finally{setBusy(false);}}
function renderResult(){const r=state.result;if(!r)return;renderLearning();$$('.editor-row').forEach((e,i)=>{e.classList.toggle('is-error',i===r.firstError-1);e.classList.toggle('selected',i===state.selected+1);});$('#path-content').innerHTML=r.steps.map((row,i)=>`<div class="path-row ${i===state.selected?'selected':''}" tabindex="0" role="button" data-path="${i}"><span class="path-icon ${row.status}">${{correct:'✓',wrong:'×',incomplete:'!',unknown:'?'}[row.status]||'?'}</span><div><h4>第 ${row.line-1} 行 <span class="minor">→</span> 第 ${row.line} 行</h4><p>${esc(row.ruleNames.join(' · ')||'符号与条件核验')}</p></div><span class="path-label ${row.status==='wrong'?'red':row.status==='correct'?'green':'amber'}">${esc(row.statusLabel)}</span></div>`).join('');$$('[data-path]').forEach(b=>{const go=()=>{state.selected=Number(b.dataset.path);renderResult();};b.onclick=go;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});renderDiagnosis(r.steps[state.selected]);$('#ast-content').innerHTML=r.ast.map((a,i)=>`<details ${i===state.selected+1?'open':''}><summary>E${i+1} · ${esc(r.normalized[i])}</summary><pre>${esc(a)}</pre></details>`).join('');plot();}
function renderDiagnosis(row){
 const r=state.result,title=row.status==='wrong'?`第 ${row.line} 行，${row.line===r.firstError?(r.firstErrorCertain?'首个错误':'最早已确认错误'):'当前步不成立'}`:row.inherited?'局部正确，仍继承前错':row.status==='correct'?'这一步，已验证正确':row.status==='incomplete'?'表达式正确，还缺收敛域':'条件不足，保留判断';
 const note=row.inherited?'局部等价不能修复之前的错误。请先返回最早出错的一步。':row.status==='wrong'?'错误位置已定位；后续推导需要从这里重新检查。':row.status==='correct'?(r.status==='correct'?'整条推导的相邻步骤均已通过。':'此结论仅适用于当前选中的相邻步骤。'):'系统不会把未完成的证明标记为正确。';
 $('#diagnosis-content').innerHTML=`<div class="result-banner ${row.status}"><div class="result-kicker"><span>${{wrong:'FIRST DIVERGENCE',correct:'VERIFIED STEP',unknown:'UNRESOLVED',incomplete:'MISSING CONDITION'}[row.status]||'CHECK'}</span><span>${row.line-1} / ${r.steps.length} 次变形</span></div><h3>${title}</h3><p>${note}</p></div>
 <div class="result-body"><div class="rule-reference"><span class="rule-id">${esc(row.ruleIds.join(' + ')||'—')}</span><strong>${esc(row.ruleNames.join(' · ')||'有界验证')}</strong></div><p>${esc(row.explanation)}</p>
 <div class="comparison"><div class="formula-box previous"><label>上一步 · E${row.line-1}</label>${formula(row.beforeLatex,row.before,row.beforeRocLatex)}</div><div class="formula-box ${row.status==='wrong'?'current':''}"><label>提交结果 · E${row.line}</label>${formula(row.afterLatex||(r.latex||[])[row.line-1],row.after,row.afterRocLatex)}</div>
 ${row.expected&&row.status!=='correct'?`<div class="formula-box expected"><label>${row.status==='unknown'?'条件成立时的候选':row.status==='incomplete'?'完整写法 · 含收敛域':'建议修正 · 同一步'}</label>${formula(row.expectedLatex,row.expected,row.expectedRocLatex)}</div>`:''}</div>
 ${row.diff?.path?`<div class="diff-line"><span>局部差异</span><span class="diff-math">${math(row.diff.beforeLatex,row.diff.before,false)}</span><span>→</span><span class="diff-math fixed">${math(row.diff.afterLatex,row.diff.after,false)}</span></div>`:''}
 <div class="evidence-tags">${[...row.evidence,...row.conditions].map(t=>`<span>${esc(t)}</span>`).join('')}</div>
 ${row.trace?.length?`<details class="trace-details"><summary>展开 ${row.trace.length} 次规则重写</summary>${row.trace.map(q=>`<div class="trace-step"><span class="rule-id">${esc(q.ruleId)}</span><div class="trace-formulas">${formula(q.beforeLatex,q.before)}<span class="trace-arrow" aria-label="规则重写">↓</span>${formula(q.afterLatex,q.after)}</div></div>`).join('')}</details>`:''}
 ${row.samples?.length?`<details class="trace-details"><summary>查看数值反例</summary>${row.samples.map(q=>`<div class="trace-step">${esc(q.at)}<code>候选：${esc(q.expected)}</code><code>当前：${esc(q.actual)}</code><span>绝对差：${Number(q.error).toPrecision(5)}</span></div>`).join('')}</details>`:''}
 ${row.expected&&['wrong','incomplete'].includes(row.status)?`<div class="repair-row"><span>只替换当前错误行<br>随后重新检查整条推导</span><button class="button primary compact repair-button" id="repair-btn">应用建议并复核</button></div>`:''}</div>`;
 if($('#repair-btn'))$('#repair-btn').onclick=async()=>{const all=steps();all[row.line-1]=row.expected;setSteps(all);toast('已修改第 '+row.line+' 行，正在复核后续步骤。');await verify();};
}
$('#copy-latex').onclick=async()=>{
 if(!state.preview||previewKey!==JSON.stringify(steps())||state.preview.some(x=>x.error))return toast('请先等待公式预览完成。');
 const source='\\begin{aligned}\n'+state.preview.map((row,i)=>`E_{${i+1}}&\\quad ${row.latex}${row.rocLatex?'\\qquad \\mathrm{ROC}:\\ '+row.rocLatex:''}`).join(' \\\\[8pt]\n')+'\n\\end{aligned}';
 try{await navigator.clipboard.writeText(source);toast('已复制 LaTeX；每行保留编号，不预设各步等价。');}catch(e){toast('浏览器未允许复制，请在支持剪贴板的 HTTPS 页面重试。');}
};
function plot(){
 const e=state.example||{},ids=state.result?.steps[state.selected]?.ruleIds||[];
 const rulePlots={C01:'convolution',C02:'convolution',C03:'linearity',C04:'linearity',C05:'convolution-shift',C06:'convolution-shift',C08:'derivative',F01:'linearity',F02:'shift',F03:'frequency-shift',F04:'scale',F06:'derivative',F07:'derivative',F08:'convolution',F09:'convolution',L01:'linearity',L02:'initial',L03:'initial',L04:'derivative',L06:'causal-shift',L07:'convolution',L09:'laplace-roc-right',L10:'laplace-roc-right',Z01:'linearity',Z05:'derivative',Z06:'convolution',Z09:'roc-right',Z10:'roc-left'};
 let key=e.plot||ids.map(id=>rulePlots[id]).find(Boolean)||({'ft-shift':'shift','ft-scale':'scale','lt-initial':'initial','z-roc':'roc-right',conv:'convolution-shift','lt-correct':'causal-shift'}[e.id])||'general';
 let svg='',caption='',legend='',label='规则与条件 · 教学示意';
 const text=(x,y,t,fill='#668a7d',size=11)=>`<text x="${x}" y="${y}" fill="${fill}" font-size="${size}">${esc(t)}</text>`;
 const path=(d,color='#268e79',dash='')=>`<path d="${d}" stroke="${color}" stroke-width="2.5" fill="none"${dash?' stroke-dasharray="'+dash+'"':''}/>`;
 const axes=(origin=80,base=137,variable='t')=>`<path d="M25 ${base}H441M${origin} 20V155" stroke="#d9e5e1" fill="none"/>${text(origin-7,170,'0','#8aa095')}${text(435,157,variable,'#8aa095')}`;
 const curve=(fn,origin=80,base=137,scaleX=42,scaleY=77)=>{let d='';for(let px=25;px<=438;px+=2){const y=base-scaleY*fn((px-origin)/scaleX);d+=(px===25?'M':'L')+px+','+y.toFixed(2);}return d;};
 const exp=t=>t>=0?Math.exp(-t):0;
 if(key==='convolution'){
  label='矩形脉冲卷积 · 教学示意';svg=`<path d="M21 105H125M21 105V39H68V105M182 105H278M182 105V39H229V105" stroke="#79ad99" fill="#e6f3ed" stroke-width="2"/><path d="M328 105L376 39L424 105Z" fill="#edf5ee" stroke="#268e79" stroke-width="2.5"/>${text(73,149,'x(t)')}${text(218,149,'h(t)')}${text(367,149,'(x * h)(t)')}${text(142,79,'*','#9aac9e',22)}${text(297,79,'=','#9aac9e',22)}${text(22,124,'0')}${text(62,124,'1')}${text(183,124,'0')}${text(224,124,'1')}${text(325,124,'0')}${text(371,124,'1')}${text(418,124,'2')}${text(368,28,'峰值 1')}`;
  caption='取 x(t) = h(t) = u(t) − u(t−1)，卷积等于两矩形的重叠长度：在 0 到 1 之间增大，在 1 到 2 之间减小。这个直观例子用于理解卷积，不是把输入中的抽象信号强行指定成矩形。';
 }else if(key==='convolution-shift'){
  label='冲激与时移 · 教学示意';svg=axes()+path('M26 137H80V59H145V137H438')+path('M26 137H200V59H265V137H438','#d38176','5 4')+path('M87 35H193','#a7c3b5')+text(121,25,'向右移 a')+text(194,170,'a');legend='<div class="chart-legend"><span>示例原信号</span><span>与 δ(t−a) 卷积</span></div>';caption='单位冲激卷积保留信号；与 δ(t−a) 卷积，则将信号延迟 a。若两个卷积输入分别平移 a、b，输出平移 a+b；留意冲激中的正负号。图示取 a>0。';
 }else if(key==='shift'||key==='causal-shift'){
  label=key==='causal-shift'?'因果时移 · 教学示意':'时移与相位 · 教学示意';svg=axes()+path(curve(exp))+path(curve(t=>exp(t-2)),'#d38176','5 4')+path('M87 34H159','#a7c3b5')+text(109,25,'延迟 2')+text(160,170,'2');legend='<div class="chart-legend"><span>x(t)</span><span>x(t−2)</span></div>';caption=key==='causal-shift'?'因果信号延迟后，在延迟时刻之前为零。单边拉普拉斯的时移结论需要相应的因果条件与门控；不能把任意非因果信号的平移直接套入公式。图中以因果指数为例。':'延迟 2 表示波形向右移；在角频率约定下，傅里叶变换乘以 e^(−j2ω)。幅度谱保持不变，相位随 ω 线性变化。图中以因果指数为例。';
 }else if(key==='frequency-shift'){
  label='调制与频谱平移 · 教学示意';svg=axes(132,137,'ω')+path(curve(t=>Math.exp(-t*t/2),132,137,32))+path(curve(t=>Math.exp(-(t-3)*(t-3)/2),132,137,32),'#d38176','5 4')+path('M146 35H217','#a7c3b5')+text(154,25,'移向 +3')+text(225,170,'3');legend='<div class="chart-legend"><span>|X(ω)|</span><span>|X(ω−3)|</span></div>';caption='乘以 e^(j3t)，频谱中心向正频率平移 3，对应 X(ω−3)。图中使用高斯幅度谱展示方向；输入信号的实际频谱由其定义决定。';
 }else if(key==='scale'){
  label='负尺度与反转 · 教学示意';svg=axes(222)+path(curve(exp,222))+path(curve(t=>exp(-2*t),222),'#d38176','5 4')+text(45,34,'反转 + 压缩')+text(281,34,'原信号');legend='<div class="chart-legend"><span>x(t)</span><span>x(−2t)</span></div>';caption='以 x(−2t) 为例，负号反转时间，绝对值 2 压缩时间。其频谱为 X(−ω/2)/2；幅度系数使用 1/|a|，不能因 a<0 而变成负值。图形仅展示这一代表性尺度。';
 }else if(key==='derivative'&&(e.id==='lt-time'||e.id==='z-index'||ids.includes('L04')||ids.includes('Z05')||ids.includes('F07'))){
  const z=e.id==='z-index'||ids.includes('Z05'),fourier=ids.includes('F07'),left=z?'n · x[n]':'t · x(t)',middle=z?'dX / dz':fourier?'dX / dω':'dX / ds',right=z?'−z · dX / dz':fourier?'j · dX / dω':'−dX / ds';label='时间加权与变换域求导 · 教学示意';svg='<rect x="20" y="49" width="120" height="64" rx="9" fill="#edf6f1" stroke="#d5e6db"/><rect x="170" y="49" width="120" height="64" rx="9" fill="#edf6f1" stroke="#d5e6db"/><rect x="320" y="49" width="120" height="64" rx="9" fill="#fff5ec" stroke="#efddca"/>'+text(40,86,left,'#477360',16)+text(188,86,middle,'#477360',16)+text(330,86,right,'#a37d5e',15)+path('M145 81H165M295 81H315','#b8ccbf')+text(106,150,z?'保留完整的系数 −z':fourier?'角频率约定下，系数为 j':'求导后，还要乘以 −1');caption=z?'Z 变换中，序号加权对应 −z·dX(z)/dz，负号和 z 都不能丢。此规则在原收敛域内使用；图示展示运算结构，不表示某条输入序列的实际波形。':fourier?'傅里叶变换中，时域乘 t 对应 j·dX(ω)/dω。它与「时域求导乘 jω」是不同性质，核对导数在哪个变量上进行。':'拉普拉斯变换中，时域乘 t 对应 −dX(s)/ds。负号来自对变换核 e^(−st) 关于 s 求导；不能把时域乘法直接变成 s·X(s)。';
 }else if(key==='derivative'){
  label='求导与变化率 · 教学示意';svg=axes(228,102)+path(curve(t=>Math.exp(-t*t),228,102,56,57))+path(curve(t=>-2*t*Math.exp(-t*t),228,102,56,57),'#d38176','5 4')+text(42,34,'上升 → 正导数')+text(315,148,'下降 → 负导数');legend='<div class="chart-legend"><span>示例高斯信号</span><span>其一阶导数</span></div>';caption='求导描述局部变化率。傅里叶的时域求导对应乘 jω；单边拉普拉斯还须保留初值项。卷积求导通常把导数放在任一侧一次，不能把两种写法相加。具体公式以当前匹配规则为准。';
 }else if(key==='initial'){
  label='边界初值 · 教学示意';svg=axes()+path(curve(t=>Math.exp(-t*.65)))+`<circle cx="80" cy="60" r="4" fill="#d38176"/>`+path('M34 60H146','#d38176','4 4')+text(146,54,'x(0⁻)')+text(233,37,'边界项不能丢失')+text(210,63,'L{x′} = sX − x(0⁻)','#268e79',14);caption='单边拉普拉斯从 0⁻ 起算，一阶导数保留 x(0⁻)，二阶导数还保留 x′(0⁻)。图中的曲线只是边界初值的示意；题目给出的初值以「已知条件」为准。';
 }else if(key==='laplace-roc-right'){
  label='拉普拉斯收敛域 · 教学示意';svg='<rect x="179" y="18" width="257" height="132" fill="#e9f5ee"/><path d="M29 105H439M271 13V153" stroke="#cadfd5"/><path d="M179 18V150" stroke="#83aa94" stroke-dasharray="5 5"/><circle cx="179" cy="105" r="4" fill="#c8796c"/>'+text(166,168,'−a')+text(261,168,'0')+text(278,29,'Im(s)')+text(389,123,'Re(s)')+text(285,61,'Re(s) > −a','#4d866c',14);caption='e^(−at)u(t) 的变换为 1/(s+a)，收敛域在极点 −a 右侧，边界不包含在内。图示取 a>0；有理式与收敛域共同描述基本变换对。';
 }else if(['roc-right','roc-left','roc-compare'].includes(key)){
  label='Z 平面收敛域 · 教学示意';
  const disc=(cx,left,title)=>`<rect x="${cx-93}" y="24" width="186" height="118" rx="7" fill="${left?'#f8faf9':'#e6f4ed'}"/><circle cx="${cx}" cy="83" r="39" fill="${left?'#e6f4ed':'white'}" stroke="#68a88c" stroke-dasharray="4 4"/><path d="M${cx-80} 83H${cx+80}M${cx} 32V133" stroke="#bcd6c9"/><circle cx="${cx+39}" cy="83" r="3" fill="#c77a70"/>${text(cx-80,16,title,'#4d7465',12)}${text(cx+44,99,'a')}${text(cx-43,163,left?'|z| < |a|':'|z| > |a|','#348265',14)}`;
  if(key==='roc-compare'){svg=disc(117,false,'右边序列 aⁿu[n]')+disc(344,true,'左边序列 −aⁿu[−n−1]');caption='同一个 z/(z−a)（a≠0）可以对应不同序列：右边序列在圆外收敛，左边序列在圆内收敛。绿色区域为 ROC，虚线圆周均不包含。不能只比较有理式就认定两个变换相同。';}
  else{const left=key==='roc-left';svg=disc(230,left,left?'左边序列 −aⁿu[−n−1]':'右边序列 aⁿu[n]');caption=left?'左边指数序列 −aⁿu[−n−1] 的 ROC 为 |z|<|a|（a≠0），绿色圆内收敛；圆周不属于 ROC。右边序列虽有相同有理式，却对应圆外区域。':'右边指数序列 aⁿu[n] 的 ROC 为 |z|>|a|，绿色圆外收敛；圆周不属于 ROC。仅给出 z/(z−a) 还不足以唯一确定序列。';}
 }else if(key==='linearity'){
  label='线性与分配 · 教学示意';svg='<rect x="24" y="48" width="119" height="65" rx="10" fill="#eff7f3" stroke="#d3e6db"/><rect x="174" y="48" width="108" height="65" rx="10" fill="#1a7d69"/><rect x="313" y="48" width="124" height="65" rx="10" fill="#eff7f3" stroke="#d3e6db"/>'+text(42,86,'αx + βh','#477360',17)+text(192,86,'线性运算','#ffffff',16)+text(327,86,'αX + βH','#477360',17)+path('M147 80H170M286 80H309','#8da99b')+text(113,150,'权重保留，运算分别作用在每一项');caption='线性运算保持加法与常数权重。漏掉一个系数、项或交叉项，都会改变表达式；涉及多个变换时，还要检查共同适用条件。图中的运算框表示抽象线性性质。';
 }else if(['z-delay','z-reversal','z-exponential'].includes(e.id)){
  const info={
   'z-delay':{title:'离散延迟 · 教学示意',input:'x[n−k]',output:'z⁻ᵏ X(z)',note:'整数延迟 k，对应负指数',caption:'双边 Z 变换中，整数延迟 k 对应乘 z^(−k)。反向写成 z^k 会把延迟与超前混淆；收敛域的 0、∞ 端点还需结合序列单独检查。'},
   'z-reversal':{title:'序列反转 · 教学示意',input:'x[−n]',output:'X(1/z)',note:'变量取倒数，ROC 半径也取倒数',caption:'序列反转的 Z 变换是 X(1/z)，不是 X(−z)。例如原环形收敛域 r₁<|z|<r₂，反转后对应 1/r₂<|z|<1/r₁，端点条件按序列另检。'},
   'z-exponential':{title:'指数加权 · 教学示意',input:'aⁿ x[n]',output:'X(z/a)',note:'a ≠ 0；ROC 半径乘以 |a|',caption:'指数加权 a^n 将变换中的 z 替换为 z/a。收敛域的半径随 |a| 缩放；变量替换后展开代数式时，要对整个分母一致替换。'}
  }[e.id];label=info.title;svg='<rect x="24" y="45" width="163" height="74" rx="10" fill="#edf6f1" stroke="#d5e6db"/><rect x="273" y="45" width="163" height="74" rx="10" fill="#f5f0f7" stroke="#e4d7e9"/>'+text(65,89,info.input,'#417b62',23)+text(305,89,info.output,'#8b6994',23)+path('M205 83H255','#b8ccbf')+text(214,68,'Z')+text(88,155,info.note);caption=info.caption;
 }else{
  svg='<rect x="27" y="47" width="112" height="65" rx="9" fill="#eef5f2" stroke="#dce9e1"/><rect x="174" y="47" width="112" height="65" rx="9" fill="#eef5f2" stroke="#dce9e1"/><rect x="321" y="47" width="112" height="65" rx="9" fill="#fff7e8" stroke="#eadfbf"/>'+text(48,85,'输入表达式','#52766a',15)+text(195,85,'核对条件','#52766a',15)+text(341,85,'有界判断','#9a813e',15)+path('M145 80H168M292 80H315','#b4c8bd')+text(64,151,'已证实 / 已反驳 / 条件缺失 / 暂无法判断','#819489',12);caption='先检查表达式结构与规则前提，再决定能够证明什么。对规则库未覆盖的形式，或缺少初值、因果等条件的推导，保留判断比猜测更可靠。此图解释验证流程，不表示输入波形。';
 }
 $('#plot-label').textContent=label;$('#plot-content').innerHTML=`<svg class="signal-chart" viewBox="0 0 460 185" role="img" aria-label="${esc(label)}">${svg}</svg>${legend}<p class="plot-caption">${caption}</p><p class="plot-note">教学图用于解释性质；当前推导的判断依据，请查看上方规则、符号重写与数值反例。</p>`;
}
function renderRules(){if(!state.catalog)return;const term=$('#rule-search').value.toLowerCase();const rules=state.catalog.rules.filter(r=>(state.ruleCategory==='全部'||r.category===state.ruleCategory)&&[r.name,r.id,r.formula,r.conditions].join(' ').toLowerCase().includes(term));$('#rules-grid').innerHTML=rules.length?rules.map(r=>`<article class="rule-card"><div class="rule-card-head"><span class="category">${esc(r.category)}</span><span class="rule-id">${esc(r.id)}</span></div><h3>${esc(r.name)}</h3><div class="rule-formula math-scroll">${math(ruleLatex[r.id],r.formula)}</div><p>适用条件：${esc(r.conditions)}</p><button data-rule="${esc(r.id)}">载入此规则的示例</button></article>`).join(''):'<div class="empty-hint">没有匹配的规则，请尝试其他关键词。</div>';$$('[data-rule]').forEach(b=>b.onclick=()=>{const r=state.catalog.rules.find(r=>r.id===b.dataset.rule);loadExample({id:'rule-'+r.id,title:r.name,category:r.category,description:r.conditions,steps:[r.exampleBefore,r.exampleAfter],context:r.exampleContext||((r.id==='L06'||r.id==='L07')?{causal:true}:{})});});}
$('#rule-search').oninput=renderRules;$$('[data-cat]').forEach(b=>b.onclick=()=>{state.ruleCategory=b.dataset.cat;$$('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));renderRules();});
function renderTestRows(){const rows=state.testResults.filter(r=>state.testFilter!=='failed'||!r.passed);$('#test-body').innerHTML=rows.length?rows.map(r=>`<tr><td><button data-test="${esc(r.id)}">${esc(r.title)}</button><small>${esc(r.id)} · ${esc(r.category)}</small></td><td><span class="badge ${r.expected}">${labels[r.expected]||r.expected}</span></td><td><span class="badge ${r.actual}">${labels[r.actual]||r.actual}</span></td><td>${r.actualFirstError?'第 '+r.actualFirstError+' 行':'—'}${r.actualFirstError!==r.expectedFirstError?'<small>预期 '+r.expectedFirstError+'</small>':''}</td><td class="${r.passed?'green':'red'}">${r.passed?'✓ 通过':'× 失败'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty-table">'+(state.testFilter==='failed'&&state.testResults.length?'当前没有失败样本。':'运行后显示真实测试结果。')+'</td></tr>';$$('[data-test]').forEach(b=>b.onclick=()=>{const test=state.testResults.find(r=>r.id===b.dataset.test);loadExample({...test,description:'验收集固定样本 · 预期 '+labels[test.expected]});});}
$$('[data-test-filter]').forEach(b=>b.onclick=()=>{state.testFilter=b.dataset.testFilter;$$('[data-test-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTestRows();});
$('#run-tests').onclick=async()=>{if(state.busy)return;state.testResults=[];state.testReport=null;$('#export-tests').disabled=true;setBusy(true);$('#run-tests').textContent='正在逐条核验…';$('#test-time').textContent='';try{const result=await request({action:'tests'},p=>{state.testResults.push(p.row);$('#test-progress').textContent=`已核验 ${p.done} / ${p.total} 条`;$('#test-progress-fill').style.width=p.done/p.total*100+'%';$('#test-passed').textContent=state.testResults.filter(x=>x.passed).length;renderTestRows();});state.testReport=result;state.testResults=result.results;const wrong=result.results.filter(r=>r.expected==='wrong'),located=wrong.filter(r=>r.actualFirstError===r.expectedFirstError&&r.actual==='wrong').length;$('#test-localization').textContent=located+'/'+wrong.length;$('#test-time').textContent=(result.elapsedMs/1000).toFixed(1)+' s';$('#test-progress').textContent=`完成 · ${result.passed} 通过 / ${result.failed} 失败`;$('#export-tests').disabled=false;renderTestRows();toast('验收完成：'+result.passed+'/'+result.total+' 通过。');}catch(e){toast(e.message);$('#test-progress').textContent='测试中断，已保留完成的记录。';}finally{setBusy(false);$('#run-tests').textContent='▶ 重新运行验收测试';}};
function download(name,content,type='application/json'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-tests').onclick=()=>{if(state.testReport)download('SignalProof-test-results.json',JSON.stringify(state.testReport,null,2));};
$('#export-btn').onclick=()=>{
 if(!state.result||state.dirty)return toast('请先验证当前推导。');
 const r=state.result,css=new URL('katex/katex.min.css',location.href).href;
 const body=`<!doctype html><html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SignalProof 验证报告</title><link rel="stylesheet" href="${esc(css)}"><style>body{font:16px/1.8 'Segoe UI','Microsoft YaHei',sans-serif;color:#213e49;max-width:900px;margin:40px auto;padding:20px}h1{color:#0c7d70}section{border:1px solid #dce6e8;padding:24px;margin:20px 0;border-radius:10px;break-inside:avoid}pre{white-space:pre-wrap;background:#f5f8f9;padding:15px}small,label{color:#70838b}.formula{overflow:auto;padding:14px 4px}.katex-display{margin:0;text-align:left}.katex-display>.katex{text-align:left}.formula-roc{display:flex;gap:16px;align-items:center;border-top:1px dashed #dce6e8;padding-top:10px}.formula-roc>span{font-size:12px;color:#70838b}.formula-box{padding:15px 18px;background:#f6faf8;border:1px solid #dce6e8;border-radius:8px;margin:12px 0}.current{background:#fff7f5}.expected{background:#eef8f3}details{margin:20px 0}@media print{body{margin:0}.formula{overflow:visible}}</style></head><body>
 <h1>SignalProof · 推导验证报告</h1><p>${esc(r.summary)}</p><small>${new Date().toLocaleString('zh-CN')} · Fourier 角频率 / Laplace 单边 0⁻ / Z 双边</small>
 <h2>推导公式</h2>${r.latex.map((tex,i)=>`<div class="formula-box"><label>E${i+1}</label>${formula(tex,state.snapshot.steps[i],r.rocLatex?.[i])}</div>`).join('')}
 <details><summary>原始表达式与已知条件</summary><pre>${esc(state.snapshot.steps.join('\n'))}</pre><pre>${esc(JSON.stringify(state.snapshot.context,null,2))}</pre></details>
 ${r.steps.map(row=>`<section><h2>第 ${row.line-1} → ${row.line} 行 · ${esc(row.statusLabel)}</h2><p>${esc(row.explanation)}</p><div class="formula-box"><label>上一步</label>${formula(row.beforeLatex,row.before,row.beforeRocLatex)}</div><div class="formula-box ${row.status==='wrong'?'current':''}"><label>提交结果</label>${formula(row.afterLatex,row.after,row.afterRocLatex)}</div>${row.expected&&row.status!=='correct'?`<div class="formula-box expected"><label>规则对应结果</label>${formula(row.expectedLatex,row.expected,row.expectedRocLatex)}</div>`:''}<p>规则：${esc(row.ruleIds.join(', '))}</p><p>证据：${esc(row.evidence.join('；'))}</p><p>条件：${esc(row.conditions.join('；'))}</p></section>`).join('')}
 <p>数值抽样通过不等于数学证明；最小错因是相对正确候选的局部结构解释，并不承诺唯一。</p><small>数学字体从网站加载；联网打开后可打印或保存为 PDF。</small></body></html>`;
 download('SignalProof-verification-report.html',body,'text/html;charset=utf-8');toast('已导出含 LaTeX 排版的可打印报告。');
};
if(document.modelContext?.registerTool){const lifecycle=new AbortController();Promise.resolve(document.modelContext.registerTool({name:'verify_signal_derivation',title:'核验信号推导',description:'将推导载入当前工作区并用符号引擎验证，更新可见证据。',inputSchema:{type:'object',properties:{steps:{type:'array',items:{type:'string'},minItems:2,maxItems:16},context:{type:'object'}},required:['steps'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input)=>{if(!Array.isArray(input.steps)||input.steps.length<2||input.steps.length>16||input.steps.some(s=>typeof s!=='string'||s.length>1200))throw Error('无效推导步骤');if(state.busy||!state.ready)throw Error('数学引擎忙碌或尚未就绪');loadExample({id:'agent',title:'自定义推导',category:'傅里叶',steps:input.steps,context:input.context||{}},false);await verify();if(!state.result)throw Error('输入未通过验证');return{status:state.result.status,firstError:state.result.firstError,summary:state.result.summary};}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
renderStaticMath();setSteps(steps());plot();switchView(location.hash.slice(1)||'verify');startWorker();
