"""Generate the submission report from measured JSON, never from preset scores."""
import collections
from datetime import datetime, timezone, timedelta
import html
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from engine.service import dispatch


def esc(value):
    return html.escape(str(value))


def table(headers, rows):
    return '<div class="table-wrap"><table><thead><tr>' + ''.join(f'<th>{esc(h)}</th>' for h in headers) + '</tr></thead><tbody>' + ''.join('<tr>' + ''.join(f'<td>{esc(c)}</td>' for c in row) + '</tr>' for row in rows) + '</tbody></table></div>'


def metric(value):
    return f"{value['rate'] * 100:.2f}% ({value['correct']}/{value['total']})" if value['total'] else '不适用'


def timing(value):
    return f'{value:.3f}' if value is not None else '无已完成测量'


def validate_measurement(report):
    """Do not mix old measurements with examples generated by changed source."""
    if not report['source'].get('unchangedDuringRun'):
        raise ValueError('Core changed during measurement; rerun benchmark first.')
    expected = dict(report['source']['files'])
    expected.update({item['path']: item['sha256'] for item in report['datasets'].values()})
    expected['data/step-oracles.json'] = report['datasets']['baseline']['oracleSha256']
    expected['tools/benchmark.py'] = report['source']['benchmarkSha256']
    for path, digest in expected.items():
        if hashlib.sha256((ROOT/path).read_bytes()).hexdigest() != digest:
            raise ValueError(f'Measurement is stale for {path}; rerun benchmark before generating the report.')


def formula(latex, fallback):
    return f'<div class="math" data-tex="{esc(latex)}">{esc(fallback)}</div>'


def main():
    report = json.loads((ROOT / 'docs/benchmark-results.json').read_text(encoding='utf-8'))
    validate_measurement(report)
    baseline = report['suites']['baseline']
    holdout = report['suites']['holdout']
    scores = baseline['uniqueMetrics']
    fixtures = json.loads((ROOT / 'data/tests.json').read_text(encoding='utf-8-sig'))
    catalog = dispatch({'action': 'catalog'})
    domains = ['卷积', '傅里叶', '拉普拉斯', 'Z变换']
    counts = collections.Counter((x['category'], x['expected']) for x in fixtures)
    sections = []
    def section(title, body):
        sections.append(f'<section><h2>{title}</h2>{body}</section>')
    section('01 · 目标与交付映射', '<p>实现一个有边界、可解释、可复现的信号推导检查系统。输入每一行表达式及条件，输出相邻步骤的局部结论、最早已确认错误、候选规则与修正建议。Web 与命令行共用同一个 Python 核心。</p>' + table(
        ['课程要求', '实现与证据'], [
            ['表达式解析器与标准化', 'engine/syntax.py：AST 白名单、原始分母、变量类型、上下文校验'],
            ['不少于30条可执行规则', f"{catalog['ruleCount']}条注册规则/映射；其中40条领域性质，另3条泛型变换映射"],
            ['步骤验证与错因定位', 'engine/verification.py + diagnostics.py：符号、规则、合法反例、首错确定性'],
            ['不少于50条正确及50条错误推导', f"data/tests.json：{sum(x['expected']=='correct' for x in fixtures)}正确 + {sum(x['expected']=='wrong' for x in fixtures)}错误；逐步标签另存step-oracles.json"],
            ['准确率及处理时间', 'benchmark-results.json/CSV：逐步、整链、首错、分领域及重复实验原始行'],
            ['完整提交工程', '命令行、Web演示、固定依赖、离线安装脚本、自动化测试、实验报告与迭代记录'],
        ]))
    section('02 · 系统结构与表示', '''<div class="pipeline"><span>安全解析<br>syntax</span><b>→</b><span>规则匹配<br>rules</span><b>→</b><span>证据核验<br>diagnostics</span><b>→</b><span>逐步与首错<br>verification</span></div>
    <p>service 负责稳定 API、目录与样本调度；formatting 只负责 LaTeX，排版失败不会改变数学结论。浏览器 Worker 装载同一组模块并在独立线程运行，原生 CLI 在可终止的子进程中运行单次请求。</p>
    <p>解析器使用 Python <code>ast.parse</code> 后逐节点白名单转换为 SymPy 树，不使用 <code>eval</code> 或 <code>parse_expr</code>。保留未化简的运算结构及分母列表；标准化在已知条件下执行代数化简、变换对代入和变量替换。原始输入、AST、标准式、LaTeX 与规则路径均可检查。</p>
    <pre>Expression := Number | Symbol | Function(Expression, ...)
            | +Expression | -Expression
            | Expression (+ | - | * | / | ^) Expression
Line       := Expression [; ROC: Condition]</pre>
    <p>每链2–16行，单表达式最多1200字符、250个AST节点、22层嵌套；数值幂和变量/函数列表另有限制。这些是输入边界，不是任意符号计算的复杂度保证；CLI与Web还提供墙钟超时隔离。</p>''')
    section('03 · 数学约定与判定流程', '''<p>Fourier 采用角频率及核 e<sup>−jωt</sup>，逆变换系数为1/(2π)；Laplace 从0<sup>−</sup>开始、保留初值；Z为双边变换、n为整数。连续时移与时间缩放采用实参数，离散时移采用整数参数。对于已知基本变换对，表达式和ROC一起比较；泛型规则未给出精确ROC时不补造条件。</p>
    <ol><li>校验输入、上下文、原始分母与ROC。</li><li>尝试直接符号等价以及有界规则重写，记录每次重写及适用条件。</li><li>不能建立证明时，在合法定义域、给定ROC与声明变换对下寻找数值反例。找到可靠反例才判错；抽样相同不判正确。</li><li>从第一对相邻行向后扫描，保存第一个确认错误的目标行号。前面若存在未知或缺失条件，置 <code>firstErrorCertain=false</code>。</li><li>将候选正确式和提交式的表达式树比较，返回局部不匹配路径。仅替换出错行，之后重新验证全部步骤。</li></ol>
    <p>“最小错因”是相对于有界搜索找到的候选，给出最小局部结构差异；并非所有等价推导中的全局最小编辑，也不承诺诊断唯一。后续局部正确步骤可标记“继承前错”，不能因此修复整链。</p>''' + table(['状态', '含义'], [['correct','有规则证明或符号等价依据'],['wrong','规则冲突、ROC冲突或合法反例'],['unknown','前提不足、能力外或证据不足'],['incomplete','代数结果成立但必要ROC缺失'],['inputRejected / error','非法语法或请求；独立于数学未知记录']]))
    section('04 · 测试数据与实验协议', table(['领域','正确链','错误链','总链数'], [(d,counts[d,'correct'],counts[d,'wrong'],counts[d,'correct']+counts[d,'wrong']) for d in domains]) +
        f'''<p>固定验收集共{baseline['cases']}条推导、{baseline['steps']}次相邻变形。错误样本覆盖相位符号、绝对值系数、初值、归一化、变量替换、运算混淆和ROC；多步样本覆盖中间首错、末步首错与错误传播。标签在运行前固定，不由被测引擎生成。</p>
        <p>扩展集另含{holdout['cases']}条组合/边界案例，单独统计。它是AI辅助构建和独立数学核对的工程回归集，未经过外部人员认证，也不是盲测学术数据集。测试集设计与独立逐步标签、失败明细随源代码公开。</p>
        <p>执行{report['protocol']['repeats']}轮，排除工作进程导入和预热。时延为一次完整验证调用的实际墙钟时间，包含解析、规则/符号计算、诊断及LaTeX输出；不包括浏览器资源下载、UI渲染、进程启动和IPC。超时作为失败保留，随后重启工作进程，不从分母删除。</p>''' +
        table(['环境项','实测值'],[(k,v) for k,v in report['environment'].items()]) +
        '<p>本报告使用首次实测计算唯一案例准确率，全部重复用于时延及稳定性检查。重复计数与首次计数分别保存在JSON中，避免将三轮100条写成300条独立题目。</p>')
    section('05 · 实测结果', table(['指标','固定验收集','扩展集'], [
        ['步骤判断准确率',metric(scores['stepAccuracy']),metric(holdout['uniqueMetrics']['stepAccuracy'])],
        ['整链状态准确率',metric(scores['chainAccuracy']),metric(holdout['uniqueMetrics']['chainAccuracy'])],
        ['错误链首错位置准确率',metric(scores['firstErrorOnWrong']),metric(holdout['uniqueMetrics']['firstErrorOnWrong'])],
        ['首错含无错链的匹配率',metric(scores['firstErrorIncludingNone']),metric(holdout['uniqueMetrics']['firstErrorIncludingNone'])],
        ['已完成调用平均处理时间 / ms',timing(baseline['latencyMs']['mean']),timing(holdout['latencyMs']['mean'])],
        ['P50 / P95 / ms',timing(baseline['latencyMs']['p50'])+' / '+timing(baseline['latencyMs']['p95']),timing(holdout['latencyMs']['p50'])+' / '+timing(holdout['latencyMs']['p95'])],
        ['超时调用数',sum(row['timedOut'] for row in baseline['rows']),sum(row['timedOut'] for row in holdout['rows'])],
        ['重复间不一致的案例数',len(baseline.get('inconsistentCaseIds',[])),len(holdout.get('inconsistentCaseIds',[]))],
    ]) + '<p>步骤准确率 = 局部状态与逐步标签相同的相邻步骤数 / 全部带标签相邻步骤数。首错位置准确率 = 同时判为wrong且首错行匹配的错误链数 / 全部预期错误链数。未输出结论和错误位置偏移均计失败。</p>' +
    '<h3>分领域结果</h3><p>下表按全部重复测量计数。时延统计只包含已完成的核心调用，超时仍保留在准确率分母及上述超时行中，不以超时上限冒充真实执行时间。</p>' + table(['领域','步骤准确率','首错准确率','已完成调用平均ms'],[(d,metric(row['metrics']['stepAccuracy']),metric(row['metrics']['firstErrorOnWrong']),timing(row['latencyMs']['mean'])) for d,row in baseline['byDomain'].items()]) +
    '<p>固定样本通过率不代表任意数学表达式的泛化准确率。性能依赖机器、SymPy版本、推导复杂度及缓存；应在提交/答辩机器上复跑，而非将本机时延当成普适指标。</p>')
    failures=baseline['failures']+holdout['failures']
    section('06 · 失败与案例解释', ('<p>本次实验记录到以下失败；保留原始输入和实际结论，未改变预期标签以提高分数。</p><pre>'+esc(json.dumps(failures,ensure_ascii=False,indent=2))+'</pre>' if failures else '<p>本次两组测量未出现与预设标签不符的案例。该结果仅覆盖此次固定数据；独立审查发现的历史缺陷已加入回归测试。</p>') + case_examples(fixtures))
    review = json.loads((ROOT/'docs/review-record.json').read_text(encoding='utf-8'))
    iterations = ''.join(f'<article class="review-item"><h3>{esc(item["title"])}</h3><p><b>发现：</b>{esc(item["finding"])}</p><p><b>修复：</b>{esc(item["change"])}</p><small>{esc(item["evidence"])}</small></article>' for item in review['rounds'])
    section('07 · 自评与迭代记录', '''<p>依据课程验收点进行自评，不虚构教师分数。每轮使用“复现输入 → 固定期望 → 最小修复 → 回归检查”，不通过放宽标签掩盖缺陷。</p>''' + iterations + '''
    <p>本轮完成标准：所有课程交付文件齐全；固定验收、独立逐步标签和边界回归可重跑；指标来自当次执行；源码哈希与报告一致；网页继续使用同一引擎。未来改进重点是更丰富的ROC集合表达、经过外部人工复核的数据集，以及更大范围的性质组合。</p>''')
    section('08 · 复现与运行', '''<pre>python tools/setup.py
# Windows: 使用 .venv\\Scripts\\python.exe 替代下面的 python
# macOS/Linux: 使用 .venv/bin/python
python -m engine verify examples/fourier-shift.json --pretty
python -m engine verify examples/z-complete.json --require-correct
python -m unittest discover -s tests -v
python tools/benchmark.py --repeats 3 --output docs/benchmark-results.json
python tools/generate_report.py
python -m engine serve --port 8080</pre>
    <p>安装脚本只使用仓库自带的SymPy/mpmath wheel，依赖版本固定。GitHub自动检查在Windows和Linux执行回归与CLI样例。命令行超时返回独立标识，不能当成已验证正确。数学核心不需要API Key，计算数据不会发往大模型。</p>
    <p><a href="benchmark-results.json">完整JSON测量</a> · <a href="benchmark-results.csv">逐次CSV</a> · <a href="../data/step-oracles.json">逐步标签</a> · <a href="../data/holdout.json">扩展案例</a> · <a href="https://github.com/zhangzhi-666/signalproof-demo">源代码</a></p>''' + table(['审计项','摘要'], [('测量完成时间（北京时间）',datetime.fromisoformat(report['generatedAt'].replace('Z','+00:00')).astimezone(timezone(timedelta(hours=8))).strftime('%Y-%m-%d %H:%M:%S UTC+08:00')),('核心源文件SHA-256',report['source']['sha256']),('基线数据SHA-256',report['datasets']['baseline']['sha256']),('逐步标签SHA-256',report['datasets']['baseline']['oracleSha256'])]))
    section('09 · 能力边界与结论', '''<p>系统覆盖课程要求的四类运算和主要变换性质，能给出相邻步骤证据、首错及修正建议，并具有可复现的完整工程入口。优先给出可信结论，而非强行覆盖所有数学表达式。</p>
    <ul><li>支持受限表达式语言；不识别自然语言证明、手写图片或任意LaTeX输入。</li><li>形式规则以相关变换/卷积存在及题设条件一致为前提。不会自动证明所有存在性定理。</li><li>ROC支持实现中列明的半平面/圆内外与基本特殊情形；复杂环域或隐式集合超出范围时保留未知。</li><li>有界搜索可能遗漏需要更多中间步骤的正确证明。抽样只用于寻找反例。</li><li>图形展示性质示意，不冒充输入信号的真实仿真。固定回归结果及自评不等同于外部评分。</li></ul>''')
    source=ROOT/'data/rule-latex.json'
    rule_tex=json.loads(source.read_text(encoding='utf-8'))
    appendix=''.join(f'<article class="rule"><h3>{esc(r["id"])} · {esc(r["name"])}</h3>{formula(rule_tex.get(r["id"],""),r["formula"])}<p>{esc(r["conditions"])}</p></article>' for r in catalog['rules'])
    section('附录 · 可执行规则目录', f'<details><summary>展开全部{catalog["ruleCount"]}条规则/映射</summary><div class="rules">{appendix}</div></details>')
    output='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SignalProof · 实验报告</title><link rel="stylesheet" href="../katex/katex.min.css"><script defer src="../katex/katex.min.js"></script><link rel="stylesheet" href="report.css"></head><body><nav><a href="../">← 项目首页</a><a href="../lab.html">验证实验室 ↗</a><button onclick="window.print()">打印 / 保存PDF</button></nav><main><header><span class="eyebrow">SIGNALPROOF / COURSE PROJECT 03</span><h1>信号推导步骤验证<br>与最小错因定位</h1><p class="subtitle">实验报告 · 模块实现、独立标签、实测性能与迭代记录</p><div class="metrics">''' + ''.join(f'<div><b>{esc(value)}</b><span>{esc(label)}</span></div>' for value,label in [(f"{scores['stepAccuracy']['rate']*100:.2f}%",'固定集 · 步骤判断'),(f"{scores['firstErrorOnWrong']['rate']*100:.2f}%",'固定集 · 首错定位'),(timing(baseline['latencyMs']['mean'])+" ms",'原生环境 · 平均每链')]) + '</div></header>'+''.join(sections)+'''<footer>SignalProof · 所有指标来自随附的原始测量。报告可由 tools/generate_report.py 重新生成。</footer></main><script>window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-tex]').forEach(e=>{if(e.dataset.tex&&window.katex)try{katex.render(e.dataset.tex,e,{displayMode:true,throwOnError:true,trust:false})}catch(_){}})});</script></body></html>'''
    (ROOT/'docs/experiment-report.html').write_text(output,encoding='utf-8')
    print('Generated docs/experiment-report.html from measured benchmark data.')


def case_examples(fixtures):
    blocks=[]
    for key in ('F02-ERR','F14-ERR','Z09-ERR'):
        case=next(x for x in fixtures if x['id']==key)
        result=dispatch({'action':'verify','steps':case['steps'],'context':case.get('context',{})})
        body=''.join(f'<div class="equation"><span>E{i+1}</span><div>{formula(tex,case["steps"][i])}'+('<small>ROC</small>'+formula(result['rocLatex'][i],'') if result['rocLatex'][i] else '')+'</div></div>' for i,tex in enumerate(result['latex']))
        error=next((x for x in result['steps'] if x['line']==result['firstError']),None)
        detail=f'<p>{esc(result["summary"])}</p>'
        if error:
            label = '规则：'+ ' / '.join(error['ruleIds'])+'；' if error['ruleIds'] else '依据：'
            detail+=f'<p>{esc(label)}{esc(error["explanation"])}</p>'
            if error.get('expectedLatex'): detail+='<p>候选修正：</p>'+formula(error['expectedLatex'],error['expected'])
            if error.get('expectedRocLatex'): detail+='<p>ROC：</p>'+formula(error['expectedRocLatex'],'')
        blocks.append(f'<article class="case"><h3>{esc(case["id"])} · {esc(case["title"])}</h3>{body}{detail}</article>')
    return ''.join(blocks)


if __name__=='__main__':
    main()
